### ISSUE TITLE
XML converter is broken

### ISSUE THREAD

**Issue by claus296** [HTV04/funkin-rewritten#21]
I have python installed, I’m not sure what the issue is

**Comment by GameVasion** [comment]
Can you say your whole error?

**Comment by GameVasion** [comment]
And also if you can, can you say your version of python?

**Comment by claus296** [comment]
> Can you say your whole error?

Python 3.10
![IMG_1235](https://user-images.githubusercontent.com/81391522/158914469-a1d9e1f1-b8a2-4c12-802f-451de5384c7a.jpeg)

**Comment by GameVasion** [comment]
Have you tried downloading a new converter? And what does the xml look like? (It may be a broken xml)

**Comment by claus296** [comment]
> Have you tried downloading a new converter? And what does the xml look like? (It may be a broken xml)

I have tried a new converter, here’s the xml

![IMG_1238](https://user-images.githubusercontent.com/81391522/158915189-ffbfc8f3-0ad0-4607-94bd-09718f301e6e.jpeg)

**Comment by GameVasion** [comment]
Idk whats happening cuz I never got this error before. I'll mention @HTV04 because he'll know more than me

**Comment by HTV04** [comment]
@claus296 Can you send the XML file? It might be broken

**Comment by claus296** [comment]
> @claus296 Can you send the XML file? It might be broken
here
https://www.mediafire.com/file/ylbz7pruhmqhjkt/MarioLand.xml/file

**Comment by HTV04** [comment]
> @claus296 Can you send the XML file? It might be broken
> here
> https://www.mediafire.com/file/ylbz7pruhmqhjkt/MarioLand.xml/file

Can you please upload the file here directly? I'm on my phone right now and it's not letting me download it from MediaFire (it's generally better to avoid MediaFire anyway because they spam people with ads).

You should be able to upload it by renaming the file extension to .txt and dragging it here

**Comment by HTV04** [comment]
I have a friend that was facing the same issue with some XMLs from the mod. Instead of just MarioLand.xml, he also reported that another XML was not working correctly with the converter. He sent me the affected XMLs and using a hex editor, I discovered that they have a really weird [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) that threw the XML parser off. Deleting it fixed the issue for both XML files.

Here are the fixed XMLs: [Fixed-XMLs.zip](https://github.com/HTV04/funkin-rewritten/files/8344346/Fixed-XMLs.zip)

If you have any other weird XMLs, let me know.
